---
abstract: 'Get a locale specific string describing the span of a given duration'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Human-Duration
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  version: 0
resources:
  repository: https://github.com/mstratman/DateTime-Format-Human-Duration
version: v0.0.1
